server:
  port: 8080
spring:
  application:
    name: webUploader
  servlet:
    multipart:
      #设置文件大小限制，默认是1M
      max-file-size: 200MB
      max-request-size: 200MB
file:
  #文件上传基础路径
  base-path: D:\workpace\spring-webUploader-file
